name: Build

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: gradle build --build-cache
      - name: Success tests
        run: gradle test --tests "com.javiersc.resources.networkResponse.tests.success.*"
      - name: Client error tests
        run: gradle test --tests "com.javiersc.resources.networkResponse.tests.clientError.*"